name: shelf_plus
description: Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
version: 1.9.2
repository: https://github.com/felixblaschke/shelf_plus

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_hotreload: ^1.5.0
  shelf_web_socket: ^2.0.0
  mime_type: ^1.0.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  dio: ^5.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
